<?php include('inc/header.php'); ?>
<section>
    <div class="container-detail">
        <div class="single">
            <article>
                <div class="article-header">
                    <h1><?php echo $post['title']; ?></h1>
                    <a class="button edit-button" href="/edit/<?php echo $post['id']; ?>">Edit Post</a>
                </div>
                <time datetime="<?php echo $post['date']; ?>">
                    Posted on <?php echo strftime("%B %e, %G at %H:%M", strtotime($post['date'])); ?>
                </time>
                <?php if (!empty($post['update_date'])) { ?>
                    <h4>
                        Last update: <?php echo strftime("%B %e, %G at %H:%M", strtotime($post['update_date'])); ?>
                    </h4>
                <?php } ?>
                <?php 
                    if (!empty($tags)) {
                        echo "<div class='tags-list'>";
                        foreach ($tags as $tag) {
                            echo "<a href='tags.php?id=" . $tag['id'] . "' class='button button-tag'>" . $tag['name'] . "</a>";
                        }
                        echo "</div>";
                    } 
                    ?>
                <div class="entry">
                    <p><?php echo $post['body']; ?></p>
                </div>
            </article>
        </div>
    </div>
</section>
<section class="entry-comments">
    <div class="container">
        <h2>Comments</h2>
        <?php if (!empty($comments)) { 
            foreach ($comments as $comment) { ?>
                <div class="comment">
                    <strong><?php echo $comment['name']; ?></strong>
                    <time datetime="<?php echo $comment['date']; ?>">
                        <?php echo strftime("%B %e, %G at %H:%M", strtotime($comment['date'])); ?>
                    </time>
                    <form action="/comment/delete" method="POST"
                        onsubmit="return confirm('Are you sure you want to delete this comment?')">
                        <input type='hidden' value='<?php echo $comment['id']; ?>' name='comment_id' />
                        <input type='hidden' value='<?php echo $post['id']; ?>' name='post_id' />
                        <input type='submit' class='button button-delete' value='delete' />
                    </form>
                    <p><?php echo $comment['body']; ?></p>
                </div>
            <?php } 
        } else { ?>
            <div class="comment">
                <h4>No comments yet. Post the first comment!</h4>
            </div>
        <?php } ?>
        
        <div class="new-comment">
            <form method="POST" action="/comment/new">
                <label for="name"> Name</label>
                <input type="text" name="name"><br>
                <label for="comment">Comment</label>
                <textarea rows="5" name="body"></textarea>
                <input type="hidden" name="post_id" value="<?php echo $post['id']; ?>">
                <input type="submit" value="Post Comment" class="button">
            </form>
        </div>
    </div>
</section>
<?php include('inc/footer.php'); ?>