<?php include('inc/header.php'); ?>
        <section>
            <div class="container">
                <div class="edit-entry">
                    <h2>Edit Entry</h2>
                    <form method="post" action="/edit">
                        <label for="title"> Title</label>
                        <input type="text" name="title" value="<?php echo $post['title']; ?>"><br>
                        <label for="entry">Entry</label>
                        <textarea rows="5" name="entry"><?php echo $post['body']; ?></textarea>
                        <input type="hidden" name="id" value="<?php echo $post['id']; ?>"><br>
                        <input type="submit" value="Save Entry" class="button">
                        <a href="#" class="button button-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </section>
        <footer>
            <div>
                <a href="#">Contact Us</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                <a href="#">Terms</a>
            </div>
        </footer>
    </body>
</html>