<?php include('inc/header.php'); ?>
        <section>
            <div class="container">
                <div class="entry-list">
                    <?php  foreach ($posts as $post) { ?>
                        <article>
                            <h2>
                                <a href="/detail/<?php echo $post['id']; ?>"><?php echo $post['title']; ?></a>
                            </h2>
                            <time datetime="<?php echo $post['date']; ?>">
                                <?php echo strftime("%B %e, %G", strtotime($post['date'])); ?> at 1:00
                            </time>
                        </article>
                    <?php } ?>
                    <!-- <article>
                        <h2><a href="detail">Dude, where’s my car?</a></h2>
                        <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</a></time>
                    </article> -->
                </div>
            </div>
        </section>
        <footer>
            <div>
                <a href="#">Contact Us</a>&nbsp;&nbsp;&bull;&nbsp;&nbsp;
                <a href="#">Terms</a>
            </div>
        </footer>
    </body>
</html>